### ISSUE TITLE
Target .NET Standard 2.0

### ISSUE THREAD

**Issue by johnrutherford** [atifaziz/Hazz#6]
It would be nice if the NuGet package also targeted .NET Standard 2.0. Otherwise a lot of extra dependencies are added if you are using this package to target a platform that is .NET Standard 2.0 compliant.

**Comment by atifaziz** [comment]
I agree.

**Comment by atifaziz** [comment]
Closed via 87de4579496925f7eb968a467af5aa2b11d34cd1 (merge of PR #7). Thank!
